### ISSUE TITLE
a lot of onchain_payment have pending: true despite being confirmed

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#11]
`db.getCollection('medici_transactions').find({"type": "onchain_payment", "pending": true}).count()` --> 356
`db.getCollection('medici_transactions').find({"type": "onchain_payment"}).count()` --> 914

looking at the log, it seems this is because the `trigger` Pod didn't receive the notification from lnd. 

similar to the cleanup function for Lightning when a payment has been sent (`updateUsersPendingPayment`), another cron job should run daily to make sure sent on-chain transaction with 6 blocks confirmation are marked `pending = false`.

**Comment by dolcalmi** [comment]
is still happening?

**Comment by nicolasburtey** [comment]
I believe so yes. this is related to the fact we don't seem to always receive events from lnd when a transaction is being confirmed. 

but I think the move to bitcoind would solve this issue: https://github.com/GaloyMoney/galoy/pull/317 @jotapea

**Comment by jotapea** [comment]
Yes these events will be emitted by enabling ZeroMQ in bitcoind https://github.com/GaloyMoney/galoy/issues/346. This solution should solve this issue.
