### ISSUE TITLE
Validate config @ startup

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#1119]

**Comment by nicolasburtey** [comment]
I think @dolcalmi had done it for the `price` repo, we may want to use the same pattern: https://github.com/GaloyMoney/price/pull/19/files#diff-b3b02c020961de6dd1193f2f53a2ddfc20578b09818ff98560b5bbfd8608c1deR29

**Comment by dolcalmi** [comment]
https://github.com/GaloyMoney/galoy/pull/1148
