### ISSUE TITLE
Expose paginated transactions at the account level for both BTC and USD wallets

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy#1199]
The Bitcoin Beach mobile app contains views which display a users past transactions.  Up to this point this has involved looking at the transactions contained in one wallet (BTCWallet), but now that we are introducing USDWallets it becomes more complex.  We now want to display to the user their last transactions across multiple wallets.  On the mobile app we could query the transactions for both wallets and merge them on the client side, but it's inefficient to do that for certain use cases, for instance if we want to display the 5 most recent transactions for an account we would need to query the 5 most recent for both the BTC and USD wallet and then merge them on client, and it could be that the past 5 transactions only took place on the USD wallet so the work to fetch the BTC transactions was unnecessary (this is the case for the move money screen).  I propose that we expose transactions at the account level which will combine the transactions in both BTC and USD wallets.

**Comment by vindard** [comment]
I was looking into a related issue with this. If we decide to go ahead, we'd need to expand the graphql `Transaction` type to include context about which wallet it's from (specifically the `WalletCurrency`).

Not sure what the boundary tradeoffs (if any) are with doing this.
