### ISSUE TITLE
Fix consistency when passing message to open-telemetry events

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy#1217]
## Description

If we have variables to pass to otel events we should add them as a separate object (like we do with logging) instead of inserting them inline to a single string.

See this example to be fixed: https://github.com/GaloyMoney/galoy/blob/c4484d39c73ffdaeac81a67692ca7f350b1e0f62/src/debug/migrate-ln-payments-listpayments.ts#L105

**Comment by nicolasburtey** [comment]
some additional context where I was looking for it @vindard, it seems those instances are only in debug script for now. I was sharing this more for future use of ` addEventToCurrentSpan` as opposed to necessary fix the one that exist. if they're just debug script it doesn't really matter
