### ISSUE TITLE
Make the myUpdates subscription work for receivers

### ISSUE THREAD

**Issue by samerbuna** [GaloyMoney/galoy#1220]
The Galoy API has a `myUpdates` subscription operation that an authenticated user can use to get instant updates about new transactions that happen under their wallets. Currently, when a transaction is settled on the Galoy backend, the `myUpdates` subscription pushes updates to the sender of that transaction. We need it to to push an update to the receiver account as well.

To test the current flow and prepare for the new feature, run the Galoy API locally and then open 3 different browser sessions for http://localhost:4002/graphql

In one session, authenticate as userA (get token and put it in HTTP headers), and as userB in another session. Then run the `myUpdates` subscription for both sessions:

```gql
subscription myUpdates {
  myUpdates {
    me {
      defaultAccount {
        wallets {
          balance
        }
      }
    }
    update {
      __typename
      ... on LnUpdate {
        walletId
        paymentHash
        status
      }
      ... on OnChainUpdate {
        walletId
        txHash
        amount
      }
      ... on IntraLedgerUpdate {
        walletId
        amount
      }
    }
  }
}
```

In the third browser session, using userA token in the HTTP headers as well, make a payment to userB (using `intraLedgerPaymentSend` mutation). You'll see that the subscription operation for userA receives an IntraLedgeUpdate payload while the subscription operation for userB does not.

userB should receive an update. This should work with LN/OnChain payments as well. Both sender and receiver should get updates about the transaction.

**Comment by nicolasburtey** [comment]
has this been resolved @samerbuna ?
