### ISSUE TITLE
be able to update config without running all the CI/CD

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#128]
right now we have to run the build to update the config. we should find a way to have a more dynamic system where it would not be needed to run the full test of suites to update a config parameter. 

if we have to run all the tests to update a parameter, it makes the point of having a config file less relevant.

**Comment by nicolasburtey** [comment]
how often does the cron runs? this would be an option indeed. 

another option would be to run a manual job on circleci to do a redeployment without having to run all the tests beforehand.
maybe this second option would be easiest to implements. we would just need to separate the build/test with the deployment, so that the latter can be run independently.

**Comment by krtk6160** [comment]
> how often does the cron runs? this would be an option indeed.

It's once every minute afaik (which is too aggressive for our use case here, but we can adjust it of course)

> another option would be to run a manual job on circleci to do a redeployment without having to run all the tests beforehand.
> maybe this second option would be easiest to implements. we would just need to separate the build/test with the deployment, so that the latter can be run independently.

Yep, I agree.
