### ISSUE TITLE
Return max fee for timed out fee probes

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#1341]
if fee probe timeout we need to return the max fee value so that we can always restrict the frontend to block sending if amount + fee is more than balance.

**Comment by nicolasburtey** [comment]
+ the "calculation unsuccessful" has been mentioned as a bug by some people.

return max fees would indeed be a lot more relevant.

we should also lower how much the node can pay in fees. I think right we may be on the default of 2%. we can probably lower this to something like 10x to 0.2%.
