### ISSUE TITLE
Onchain payment createdAt date is invalid prior to confirmation

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy#1399]
**Steps to reproduce:**
1. Receive an onchain payment to your BBW account
2. Query account for transactions
3. See that createdAt date field is populated with: `{"extensions": [Object], "message": "Invalid value for Date"}`

I think it might have something to do with the following code but I'm not sure.
https://github.com/GaloyMoney/galoy/blob/e2ad50613fa26137d70a0488c0f422b9b8835347/src/services/lnd/onchain-service.ts#L223

**Comment by nicolasburtey** [comment]
not an issue anymore
