### ISSUE TITLE
Calculation Unsuccessful preventing confirming payments

### ISSUE THREAD

**Issue by kri8or** [GaloyMoney/galoy#1439]
**Title**
Calculation Unsuccessful preventing confirming payments

**Description**
Unable to use the wallet due to this issue

| Date added    | Bounty Amount |
|---------------|---|
|  |   |

**Comment by vindard** [comment]
@kri8or was this resolved or are you still getting this?

**Comment by daviroo** [comment]
Will close this issue due to inactivity.  I think we had an issue displaying errors related to fees which should be fixed in the most recent release.
