### ISSUE TITLE
make it possible to "send all" amount for onchain payment

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#16]
currently, when making a payment, the fees are being added to the amount sent. 

for instance, if someone want to send 10,000 sats, and the fees is 2,000, the total will be 12,000 sats. 

the issue to do a send all is that, when the base amount increase, the fee might changes (fee are being calculated dynamically by lnd). 

so for instance, if someone has 15000 sats. he would need to have maybe 13000 sats in the amount, and if the fees are 2000 sats then this would send all. but maybe for 13,000 sats the fees would be 2050 because one utxo is being used. and for 12950, only 2000 would be necessary because a single utxo would be needed. 

so empirically people are doing a dichotomy to find the right amount to swipe their balance. I believe the right way to manage is to have a send_all flag where instead of the fees being added, it should be deduced from the total amount sent.

this would have an impact on the react native side. but first the API should be available for consumption to the mobile wallet.

**Comment by jotapea** [comment]
Hello @nicolasburtey. I'll be working on this as my first open source contribution, thank you for the opportunity! Also, this is my first kubernetes and typescript project, so I will need to get up to speed on these.

I believe that this is the lightning library function that will allow to "send all": https://github.com/alexbosworth/ln-service#sendtochainaddress

And I am looking at this function call in the onChainPay method, https://github.com/GaloyMoney/galoy/blob/main/src/OnChain.ts#L171

But I am "stuck" at the moment. The problem I am having is that my IDE (Visual Studio Code) is showing an error when trying to add the 'is_send_all' parameter to the sendToChainAddress lightning function. I think is most likely related to typescript, which I am still learning.

I have some commits locally and I could do a PR to show you how I am progressing, but you tell me how you prefer to move forward.

**Comment by jotapea** [comment]
@nicolasburtey I was able to remove the IDE error by deleting node_modules, so at least that is a temporary solution.

Now I need to know how you plan on handling the "this.user.withdrawFee". Will this also be deducted from the 'amount', or does the user need to have enough funds to cover the 'amount' specified + the withdrawFee?

**Comment by nicolasburtey** [comment]
probably https://github.com/alexbosworth/lightning should be used instead of https://github.com/alexbosworth/ln-service. the first one has typescript definition.

the send_all you are referring to is from lnd perspective. we want to activate this option at the user level. 

> Will this also be deducted from the 'amount', or does the user need to have enough funds to cover the 'amount' specified + the withdrawFee?

basically the fees needs to be deduced from the balance of the user. as opposed to the current flow where fees are added to the payment being sent.

**Comment by jotapea** [comment]
Ok then should I be looking at this pay method (https://github.com/GaloyMoney/galoy/blob/main/src/Lightning.ts#L346), or not?

If it is, then I see functions like addTransactionLndPayment which goes into using medici...

Next I'll study what is happening here, or let me know if you recommend something else.

**Comment by nicolasburtey** [comment]
> Ok then should I be looking at this pay method (https://github.com/GaloyMoney/galoy/blob/main/src/Lightning.ts#L346), or not?

this is for lightning payment. the idea is to have send all for onchain payment. so this would be in the onchain.ts file.

**Comment by jotapea** [comment]
Made some progress, here is what I have so far: https://github.com/jotapea/galoy/pull/1/files

**Comment by jotapea** [comment]
Hello @nicolasburtey. Can you let me know if I am in the correct path?

https://github.com/jotapea/galoy/pull/1/commits/ad68a1a6ada1513b2c77f1629f70eccdaa4b45bc

Are the assumptions specified in this last commit correct? And fyi, I can make a new cleaner branch with these changes for the PR to the official repo.

**Comment by jotapea** [comment]
@nicolasburtey thanks for the feedback in https://github.com/jotapea/galoy-test/pull/1#pullrequestreview-693195971 (new link).

So I made a new PR based on the feedback and because the code changed. But today the code changed again, and there are merge conflicts now. But up this point the tests are passing for me. Let me know if I should rebase or how to proceed.

New PR: https://github.com/GaloyMoney/galoy/pull/274/files

**Comment by jotapea** [comment]
@nicolasburtey Let me know if the way I did the rebase is how you want. I am used to using new branch names / PRs for rebases, but in this open source environment I assumed is better to keep the original branch name. But while doing this, it closed the PR 🤦. Is this ok? lol

So, here is the new PR: https://github.com/GaloyMoney/galoy/pull/275/files

Here are the comments from the original PR that should still apply:
- https://github.com/GaloyMoney/galoy/pull/274#issuecomment-870677972
- https://github.com/GaloyMoney/galoy/pull/274/files#r660053340
- https://github.com/GaloyMoney/galoy/pull/274/files#r660055663

**Comment by dolcalmi** [comment]
can we close this issue?

**Comment by nicolasburtey** [comment]
close this issue as this has been completed on the backend
