### ISSUE TITLE
kratos upgrade

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#1877]
immediate work:

- ~~migrate inc to new terraform (with postgres update)~~

- move webwallet to use cookie e2e
-- need to activate cookie
-- problem: no graphql endpoint for cookie when there need to be a captcha

- ~~log out from the mobile app should expire the associated session~~

- add a call to deactivate all sessions for a particular user/account from the admin panel

- (oathkeeper) pass public key from oathkeeper to api via env variable instead of the current fetch from api after has started --> would reduce potentially transient error on api startup

**Comment by nicolasburtey** [comment]
Also needed: kratos in BigQuery @bodymindarts

**Comment by bodymindarts** [comment]
> Also needed: kratos in BigQuery @bodymindarts

This is done.

**Comment by sandipndev** [comment]
> (oathkeeper) pass public key from oathkeeper to api via env variable instead of the current fetch from api after has started --> would reduce potentially transient error on api startup

Chart part done in https://github.com/GaloyMoney/charts/pull/1971
Require changes to backend and adding of `OAUTHKEEPER_PUBLIC_KEY` env on backend and appropriate logic.

**Comment by nicolasburtey** [comment]
also: look at the bootstraping environment with kratos / email

**Comment by nicolasburtey** [comment]
closing this meta ticket
