### ISSUE TITLE
missing fees/ revenues in the accounting books

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#20]
are missing (at least):

- fee accounting for loop server
- miner fee from cold storage to hot wallet

**Comment by nicolasburtey** [comment]
routing has been done

**Comment by dolcalmi** [comment]
miner fee from cold storage to hot wallet was included too https://github.com/GaloyMoney/galoy/blob/main/src/app/wallets/update-on-chain-receipt.ts#L152
