### ISSUE TITLE
use lnd status endpoint with lnd 0.13

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#206]
our current check rely on getWalletInfo() to see if lnd is alive or not. lnd 0.13 has a new getState that should put less strain on lnd (not requiring to fetch some some state) so we should move to [getState](https://api.lightning.community/#getstate) instead

(lnd would needs to be upgrade to 0.13 before being able to do this)

**Comment by krtk6160** [comment]
Closed on the [charts repo](https://github.com/GaloyMoney/charts/pull/58)
