### ISSUE TITLE
Price return from backend have rounding issue

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#2119]
`{"price": {"__typename": "PricePayload", "errors": [], "price": {"__typename": "Price", "base": 16827500000, "currencyUnit": "USDCENT", "formattedAmount": "0.016827500000000002", "offset": 12}}}`

from: 

```
  subscription ($input: PriceInput!) {
    price(input: $input) {
      price {
        base
        offset
        currencyUnit
        formattedAmount
      }
      errors {
        message
      }
    }
  }
``` 
in the mobile app

**Comment by nicolasburtey** [comment]
issue is `0.016827500000000002`

**Comment by dolcalmi** [comment]
closed because `formattedAmount` is deprecated
