### ISSUE TITLE
Configs repository private

### ISSUE THREAD

**Issue by chdwlch** [GaloyMoney/galoy#220]
Trying to see if I can run this locally. Unable to access the configs repository to finish setting everything up.

https://github.com/GaloyMoney/galoy/blob/17985469071b12b951751aa2bb0fbae5a4e47f64/exportLocal.sh#L49
https://github.com/GaloyMoney/galoy/blob/17985469071b12b951751aa2bb0fbae5a4e47f64/initLocalTest.sh#L108

**Comment by nicolasburtey** [comment]
good catch. the repo contain some of the info for the prod environment. we will refactor so that it's not needed for local dev.

**Comment by krtk6160** [comment]
@chdwlch Can you pull master and retry? I've pushed a few commits that should fix the problem. Were you running one of the `yarn` commands inside `package.json`?

**Comment by krtk6160** [comment]
@chdwlch Thanks for reporting this issue. Could you please checkout #224 and see if it solves your issue?

**Comment by chdwlch** [comment]
ran `yarn add-charts` on https://github.com/GaloyMoney/galoy/pull/224 and the pods came up successfully!

```kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY   STATUS      RESTARTS   AGE
default       bitcoind-0                              1/1     Running     0          18m
default       galoy-admin-panel-7c777c9d99-5t4t2      2/2     Running     0          15m
default       galoy-lnpage-dcc859664-2998v            2/2     Running     0          15m
default       galoy-lnpay-7c5578cf49-ld8hz            1/1     Running     0          15m
default       galoy-mongodb-7b68988f86-2tlhf          1/1     Running     0          15m
default       galoy-price-76d7d8cbb5-bmlxx            1/1     Running     0          15m
default       galoy-redis-node-0                      2/2     Running     0          15m
default       lnd-0                                   1/1     Running     0          17m
default       lnd-export-secrets                      0/1     Completed   0          17m
default       lnd-lndmon-cbfbbbb9c-q78wz              1/1     Running     0          17m
default       lnd-outside-1-0                         1/1     Running     0          16m
default       lnd-outside-1-export-secrets            0/1     Completed   0          16m
default       lnd-outside-1-lndmon-7ff99df69c-rqq5z   1/1     Running     0          16m
default       lnd-outside-2-0                         1/1     Running     0          16m
default       lnd-outside-2-export-secrets            0/1     Completed   0          16m
default       lnd-outside-2-lndmon-65bf6bf8d4-g2dm6   1/1     Running     0          16m
kube-system   coredns-74ff55c5b-fmdr8                 1/1     Running     1          28h
kube-system   etcd-minikube                           1/1     Running     1          28h
kube-system   kube-apiserver-minikube                 1/1     Running     1          28h
kube-system   kube-controller-manager-minikube        1/1     Running     1          28h
kube-system   kube-proxy-65x6p                        1/1     Running     1          28h
kube-system   kube-scheduler-minikube                 1/1     Running     1          28h```

**Comment by otech47** [comment]
Not sure how exactly this bug got reintroduced it's not clear from the blame but latest `main` branch has a initLocalTest.sh that depends on the private config repo: https://github.com/GaloyMoney/galoy/blame/main/initLocalTest.sh#L137

Setting my own /configs repo and commenting out the RTL-Config.json line fixed the issue as a workaround for me

**Comment by nicolasburtey** [comment]
@bodymindarts @krtk6160 seems there are still some setup issues?

**Comment by bodymindarts** [comment]
@otech47 we have moved away from the k8s dependency for local dev. Does [this guide](https://github.com/GaloyMoney/galoy/blob/main/DEV.md) help you in what you are trying to achieve?

**Comment by otech47** [comment]
> @otech47 we have moved away from the k8s dependency for local dev. Does [this guide](https://github.com/GaloyMoney/galoy/blob/main/DEV.md) help you in what you are trying to achieve?

I will try that guide and see. I was able to get some progress using minikube not knowing which method was best but ran into this problems with the `yarn add-charts` command and that's how I resolved it. Will try the other method sometime

**Comment by nicolasburtey** [comment]
stale -- assuming this issue has been fixed by then. please reopen if that's not the case
