### ISSUE TITLE
`slowFindByPhone` does not iterate over all identities

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy#2272]
The `slowFindByPhone` function uses the buggy `listIdentities` kratos admin function that does not return the entire list. 

Possible solution:
> Yeah it is most likely not returning the last page of identities (kratos bug) . If we change the code to use the service wrapper in `IdentityRepository` it should work (because we added a workaround to get the last page)

```
import {IdentityRepository } from "@services/kratos"

 const identites = await IdentityRepository().listIdentities()
```

_Originally posted by @ntheile in https://github.com/GaloyMoney/galoy/issues/2260#issuecomment-1410692551_

**Comment by nicolasburtey** [comment]
this function has been deleted
