### ISSUE TITLE
Enforce consistent code-style

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#235]
With the help of [ESlint](https://eslint.org) and [prettier](https://prettier.io) we should document and enforce a consistent code style. This will help focus discussion on functionality critical stuff when doing code review.

Initially adding the tools will cause quite a big diff. But I think its worth the 1 time cost.

**Comment by bodymindarts** [comment]
Some useful docs:
[eslint ts plugin](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md)

cc @samerbuna incase you wanted to work on this.

**Comment by nicolasburtey** [comment]
this one is done now
