### ISSUE TITLE
Bug with contact update

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy#2431]
When a bbw user makes a payment to another bbl user with their username, the contact gets saved for both parties. However, when a bbw user generates a btc lightning invoice and another bbw user pays it, we don't save the user as a contact. Whereas, the data returned in the transactions list shows the settlement counterparty (i.e. the username of the payer and payee).

We want to also save contacts if a lightning payment is made between two bbw users. 
Below is @nicolasburtey experience on this

-- recipient showed me a lightning QR code from BBW
-- sender paid the invoice from BBW

--> transaction detail show the username of the recipient for the sender in Transaction Detail
--> transaction detail show the username of the sender for the recipient in Transaction Detail

--> unexpetedly
--> username for sender not present to the recipient list in Contact list
--> username for recipient not present to the sender list in Contact list

**Comment by tonyguesswho** [comment]
@Extheoisah  Please would like to work on this, can I go ahead

**Comment by Extheoisah** [comment]
Hi @tonyguesswho Yeah, sure. It'd be best to sync with @vindard and @dolcalmi (cc @nicolasburtey) as they have more context on the structure of the backend. Feel free to join the Mattermost channel here -> https://chat.galoy.io/galoy/channels/dev to get real time updates and support along the way.
