### ISSUE TITLE
adding lint in the CI environment

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#249]
the tests currently run in a [distroless container](https://github.com/GaloyMoney/galoy/blob/main/Dockerfile-debug), which is not the best environment to add external tools such as yarn or eslint. I've revert the lint as part of the circleci process for now so that the build can pass

I think the best would be to run the lint tests on a circle action.

@samerbuna

**Comment by nicolasburtey** [comment]
linked to #235

**Comment by bodymindarts** [comment]
I suggest adding this as a GitHub action together with the integration tests. I’ll get it done in the next days

**Comment by bodymindarts** [comment]
I mean Samer can do it too I just think it would be better on a GitHub action

**Comment by nicolasburtey** [comment]
done
