### ISSUE TITLE
build failure at $yarn add charts

### ISSUE THREAD

**Issue by Rice-from-data** [GaloyMoney/galoy#251]
Hi, I'm trying to deploy galoy on an Ubuntu20.04 VM. 

Node.js was installed using NVM. 
Yarn was installed using the https://dl.yarnpkg.com/debian repository.
Helm and Minikube installed from source.

`
galoy@galoymoney:~/galoy$ yarn add charts
yarn add charts
yarn add v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
warning charts > MD5@1.2.0: deprecated, use lowercase 'md5@2.x' from now on
warning charts > exeq > win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
warning charts > phantom@0.5.7: This package is no longer maintained
warning charts > express-scaffold > jade@1.1.5: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning charts > express-scaffold > less-middleware@0.1.15: Updated API and improved functionality.
warning charts > express-scaffold > jade > transformers@2.1.0: Deprecated, use jstransformer
.
.
.

make: *** [weakref.target.mk:109: Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/galoy/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-74-generic
gyp ERR! command "/home/galoy/.nvm/versions/node/v14.17.1/bin/node" "/home/galoy/.nvm/versions/node/v14.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/galoy/galoy/node_modules/weak
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
`

I see a lot of warnings and then a build error at the end. I've tried using 

`yarn add chart.js@latest`

Before this step, but that has not changed the error.

**Comment by krtk6160** [comment]
It's `yarn add-charts`, not `yarn add charts`. The latter will install a module called charts.

**Comment by nicolasburtey** [comment]
hey @Rice-from-data closing this one. feel free to reopen if you still have issues

**Comment by Rice-from-data** [comment]
Thanks so much for your response. I fat fingered that command.
