### ISSUE TITLE
our lnd doesn't reconnect to other node that are solely on tor

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#264]
needs investigation for why this is the case. previously tor nodes would auto-reconnect to us, but this is no longer the case. adding a tor connection may help to solve this issue.

**Comment by krtk6160** [comment]
Is this still an issue?

**Comment by nicolasburtey** [comment]
I think so?

**Comment by nicolasburtey** [comment]
This has been fixed
