### ISSUE TITLE
better test infrastructure on the multi lnd part

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#273]
currently we don't dynamically test having one lnd being offline and see how the app reacts. have done some manual testing but we need to automate it.

not straightforward because we need to be able to set an node offline on the fly and restart it, but the test infrastructure is already using 2 different backend, kubernetes and docker-compose.

**Comment by bodymindarts** [comment]
As the target of the test is the backend code I think having this test run only in the local setup (ie docker-compose) should be enough to ensure the code is working as expected.

I wrote a test framework [delmo](https://github.com/bodymindarts/delmo) that addresses exactly this use-case. I used it in the the past to test dynamic re-configuration of database clusters when facing node failure.

The code is unmaintained but probably wouldn't be much work to bring it up-to-date. Or perhaps it is still working as-is.
