### ISSUE TITLE
Improve testing structure

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#282]
To start improving our test setup we want to bring the folder structure in line with common practices:
```
__tests__/{integration,helpers,...}
src
```
In other words `__tests__` should be at the root not inside `src`. The current long running test should go under `test/integration` as it depends on the runtime dependencies.

This opens up the possibility to create a new folder structure that mirrors the folders under `src` with 1 file per file in the production code for unit testing.

All tasks and build steps that depends on the current folder structure will need reviewing and adapting.

This was discussed as a first step to improve the testing with @dolcalmi.

**Comment by nicolasburtey** [comment]
I don't think it's wise to put `__tests__` outside of `src/`. a lot of the config file that are within `src` (tsconfig, package.json, node_modules...) are necessary to run the tests. and they are within `src/`

**Comment by bodymindarts** [comment]
All of the files you mention are in the root of the repo not within src. 🤔

**Comment by bodymindarts** [comment]
To be clear I am proposing to move to this kind of structure:
```
$ tree repo
repo
├── __tests__
│   ├── fileTest.ts
│   ├── helpers
│   ├── integration
│   │   └── integrationTest.ts
│   └── subfolder
│       └── otherFileTest.ts
├── package.json
└── src
    ├── file.ts
    └── subfolder
        └── otherFile.ts
```


This is a [very](https://github.com/reduxjs/redux) [common](https://github.com/lodash/lodash) [structure](https://github.com/bitcoinjs/bitcoinjs-lib) in the [node js](https://github.com/nodejs/node) [ecosystem](https://github.com/npm/cli).

**Comment by nicolasburtey** [comment]
oups yeah you're right! nevermind my comment above.

**Comment by krtk6160** [comment]
Should probably use `tests` as the dir name instead of `__tests__`.

**Comment by bodymindarts** [comment]
To apply the common pattern `test` is probably the right name.

**Comment by krtk6160** [comment]
You're right, I misremembered the name.

**Comment by nicolasburtey** [comment]
`__tests__` is the default folder for jest AFAIK. this can be overridden of course.

**Comment by bodymindarts** [comment]
I don't really care what the folder name is `__tests__` or `test` or whatever... my point is regarding the structure.

**Comment by nicolasburtey** [comment]
yup ok. this would also simplify what needs to be in the production docker image. right now we have an ugly script to delete the __tests__ folders: https://github.com/GaloyMoney/galoy/blob/9f4c4ebdcb186664f500ea5420218e3b2b38d047/Dockerfile#L13

**Comment by bodymindarts** [comment]
> yup ok. this would also simplify what needs to be in the production docker image. right now we have an ugly script to delete the tests folders:

Yup that's a big reason why I prefer this structure
