### ISSUE TITLE
twilio callback

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#284]
Twilio have a callback mechanism to be able to have more data on whether text has been successfully sent or not. This would be very helpful to understand how to improve deliverability.

related to #266

**Comment by jrbuhl93** [comment]
Do you want this information logged in pino?

**Comment by nicolasburtey** [comment]
log would be useful, but it would more relevant to attach this metadata to the PhoneCode collection, to know if a particular text has been received or not easily.

for instance we don't know if some users have log in issue after retrying to log in to their account, as opposed to only user who never had log in have text issues (the first option would be worst than the second, but we don't know how much % this represents currently)

**Comment by nicolasburtey** [comment]
we should also look at if SMSAla has a similar callback option.
