### ISSUE TITLE
Set fallbackRule to deny by default

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#292]
To ensure API security, it is recommended to set fallbackRule to deny (or custom rule) in GraphQL Shield and enforce the use of rules for each query / mutation

refs:
https://graphql-shield.vercel.app/docs/advanced/whitelisting
https://github.com/maticzav/graphql-shield/issues/211#issuecomment-450636577

**Comment by nicolasburtey** [comment]
we have proper js to enforce this now afaik
