### ISSUE TITLE
Dev environment does not work if repo is cloned in a different directory

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#303]
I guess is the implementation of `fetch_macaroon` and `fetch_pubkey` in `.envrc`

maybe just change the filter from:

```
local container_id=$(docker ps -q -f status=running -f name="galoy_$1_")
```
to
```
# tested on linux but not sure about mac
local container_id=$(docker ps -q -f status=running -f name="${PWD##*/}_$1_")
```

**Comment by nicolasburtey** [comment]
do you want to make a PR? I can test it out on mac.

**Comment by dolcalmi** [comment]
> do you want to make a PR? I can test it out on mac.

if you can test it would be great... basically is to run `echo ${PWD##*/}` in the console and verify that returns the current directory name

**Comment by nicolasburtey** [comment]
seems to work: 
```
galoy nicolas$ echo ${PWD##*/}`
galoy
```
