### ISSUE TITLE
Use bignumber.js (or similar) for fee calculations and dealer

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#306]
javascript is not good with big numbers calcs

refs:
- well-known issue
- https://itnext.io/lets-talk-about-big-numbers-in-javascript-b0a2c8edb170
- https://github.com/MikeMcl/bignumber.js/

**Comment by nicolasburtey** [comment]
I think we could just used the internal bigNum library of javascript now. don't need an external dependancy. 

related: https://github.com/GaloyMoney/galoy/issues/39

**Comment by dolcalmi** [comment]
maybe with integers we have no problems but feeRatio has decimals, so this need to be reviewed carefully

**Comment by nicolasburtey** [comment]
even with integer this would be useful to have bigint I think. it's not possible to have 21m milli sats in integer for instance. 

I started working on a PR for this multiple months ago but it as I was going it was starting to be a bigger refactor than I anticipated so I moved on to some more urgent things
