### ISSUE TITLE
Add Albanian Lek (ALL) as display currency

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy#3121]
User request: https://t.me/blinkbtc/2822
https://en.m.wikipedia.org/wiki/Albanian_lek

**Comment by HostFat** [comment]
Thanks :)

**Comment by agbegin** [comment]
Please add Danish Kroner (DKK) as well https://en.wikipedia.org/wiki/Danish_krone

**Comment by vindard** [comment]
Adding notes for rates from our different sources

**ALL**
- free-currency-rates-usd: `100.40647908`
  https://github.com/fawazahmed0/currency-api/blob/1/latest/currencies/usd/all.json
- exchangeratehost: `100.76768`
  https://api.exchangerate.host/latest?base=USD&symbols=ALL
- currency-beacon: `99.74121953`
  https://api.currencybeacon.com/v1/latest?base=USD&symbols=ALL&api_key=<your-key-here>

**DKK**
- free-currency-rates-usd: `6.85691253`
  https://github.com/fawazahmed0/currency-api/blob/1/latest/currencies/usd/dkk.json
- exchangeratehost: `6.853807`
  https://api.exchangerate.host/latest?base=USD&symbols=DKK
- currency-beacon: `6.84502756`
  https://api.currencybeacon.com/v1/latest?base=USD&symbols=DKK&api_key=<your-key-here>
