### ISSUE TITLE
get master accounts and sub account for enterprises

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#313]
one of the request we have got from El Salvador is the possibility to have multiple accounts for enterprises.

Think of a chain of restaurant. The owner would like to have each restaurant with a wallet, and be able to know easily the total balances of all the wallet. Currently, an owner would have to open different wallet and each wallet would need its own access. Maybe at the end of day the restaurant would sent the balance back the "main" wallet.

I don't think the "meta" enterprise account would be manage through our current mobile wallet necessarily, but maybe the individual wallet would.

Note: this could be a paid functionality for the enterprise

**Comment by bodymindarts** [comment]
We could solve this via introducing a more sophisticated RBAC model.
Roles like wallet-viewer, wallet-admin... or something like that.
Do you know if https://github.com/maticzav/graphql-shield supports this kind of use case?

**Comment by dolcalmi** [comment]
> We could solve this via introducing a more sophisticated RBAC model.
> Roles like wallet-viewer, wallet-admin... or something like that.
> Do you know if https://github.com/maticzav/graphql-shield supports this kind of use case?

or maybe just a solution in the top of galoy core (backend)? something that offer account management, payment reports by wallet/whole account, accounting reports, taxes, POS integration, etc...

**Comment by dolcalmi** [comment]
Also I think that if we will add enterprise accounts to the core must have a different approach.. Ex:

- for transactions: create/approve/release transactions (invoice payments, payroll, btc/usd conversion). This is important for large companies
- Batch payments (integrated with invoice electronic invoice systems, ERPs, or just allowing access to the API )
- Add multiple accounts for accounting issues (but not for employees)
- etc

**Comment by bodymindarts** [comment]
I think re should certainly do some model discovery around this feature set before implementing anything to get a better understanding of what we do / don't want to be. I think implementing a whole accounting system within Galoy is probably going a bit for. Integration with existing enterprise systems is a better approach. But certainly need to be aware of the trade offs and boundaries

**Comment by nicolasburtey** [comment]
I think think like tax and accounting for indivual/companies should not be done within our core system, but could be built on top of our API by us or some other companies when we have a mature API. I don't think those element should be part of a core banking solution. (we still need to do accounting obviously, but this is to maintain the ledgers of the customer deposits)

But things like having multiple account per user and delegation of account access I think could be part of our core banking system.

**Comment by nicolasburtey** [comment]
this is mostly done. will add more granular issue as needed
