### ISSUE TITLE
Receive payments less than $0.01 to BTC account, regardless of default account

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy#3164]
Payers are having issues sending small amounts of sats to people with Stablesats set as default. Error is thrown: "Amount sent was too low for recipient's USD wallet" 

Instead of throwing error, we should receive the sats, and put them into the receiver's Bitcoin account. If we reject payments, it could cause many issues with adoption (onboarding, zapping, thundr games, etc)

**Comment by vindard** [comment]
Fixed here: https://github.com/GaloyMoney/galoy/pull/3176

**Comment by vindard** [comment]
Deployed to production, should be working now
