### ISSUE TITLE
Consent bugs

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#3399]
enter should activate 'Next' on email input
code submission should auto 'submit' (when 6 chars are in)
error management

**Comment by nicolasburtey** [comment]
2 others things to manage:
- we should have a dark mode, so that we don't switch back and forth with the dashboard in darkmode
- whatsapp login

**Comment by nicolasburtey** [comment]
we should also have a `create account` link (it can be the same as login with phone)

**Comment by nicolasburtey** [comment]
those issues have been addressed
