### ISSUE TITLE
Dashboard bugs

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#3406]
if the token is invalid, it shows a blank page instead of showing an error / redirecting to the auth page

**Comment by nicolasburtey** [comment]
also: logout fully logout. need to log out from hydra in addition to removing the cookie from next-auth

**Comment by openoms** [comment]
Two UX things to note:
- shows `Create Next App` as the page title:
![image](https://github.com/GaloyMoney/galoy/assets/43343391/8224500a-9250-4994-b409-939226ee2d0c)

- a 11 sats balance shows in scientific notation:
![image](https://github.com/GaloyMoney/galoy/assets/43343391/65401095-fe43-40e2-84d9-81c0e9670fda)

**Comment by nicolasburtey** [comment]
those issues has been addressed
