### ISSUE TITLE
Inject config via constructor

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#343]
As part of a larger refactoring to decouple from global state we want to move to injecting config via constructor arguments instead of referencing it directly via the `yamlConfig` global variable.

https://github.com/GaloyMoney/galoy/pull/321 is a PR that introduces the pattern.
We can introduce the same pattern incrementally across the whole code base.

cc @vindard

**Comment by vindard** [comment]
I'm currently tackling this through a series of smaller PRs

- [x] `SpecterWallet` class (PR #344)

- [x] `UserWallet` class (PR #370)

- [ ] `ILndParams`& lnd inputs
  - Create the [lnd mapping config]((https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/lndAuth.ts#L23)) in `config.ts` instead

- [ ] Rate limits
  - Do explicit [RateLimiter configs](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/rateLimit.ts#L5) and a getter functions

- [ ] `schema.ts`
  - [Pull in](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/schema.ts#L258) already created TransactionLimits config
  - Create a [_fees_ config](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/schema.ts#L59)

- [ ] `text.ts` & `user.ts`
  - Pass test accounts ([here](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/text.ts#L73) and [here](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/test/helpers/user.ts#L9)) as config

- [ ] `utils.ts` & `graphql-server.ts`
  -  Create explicit configs for IPs objects ([here](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/utils.ts#L170) and [here](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/entrypoint/graphql-server.ts#L65)) and [constants required](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/utils.ts#L28)

- [ ] `walletFactory.ts` getFunderWallet function
  - Revisit and potentially pass config as explicit argument [to function](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/walletFactory.ts#L41)

- [ ] `graphql-core-server.ts`
  - Include [limits](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/entrypoint/graphql-core-server.ts#L155) and [fees](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/entrypoint/graphql-core-server.ts#L161) configs that would've been created in prior PRs

- [ ] Update tests to use new config value where applicable
  - [`02-index.spec.ts`](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/test/integration/02-user-wallet/02-index.spec.ts#L39)
  - [`02-send-onchain.spec.ts`](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/test/integration/02-user-wallet/02-send-onchain.spec.ts#L114)
  - [`graphql.spec.ts`](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/test/integration/entrypoint/graphql.spec.ts#L8)

**Comment by bodymindarts** [comment]
This is a great overview.
Reviewing some other code I was thinking perhaps we should generally re-think how the `test_accounts` are being configured and user. I don't like the logic around them in the production code and the way they are hard coded and implicitly referenced. Lets make sure to do a sync around that before you get there (or do those last if we don't find time).

**Comment by vindard** [comment]
Gotcha, moved that `test_accounts` task down to the bottom of the list
