### ISSUE TITLE
Listen to bitcoind with ZeroMQ

### ISSUE THREAD

**Issue by jotapea** [GaloyMoney/galoy#346]
Use [ZeroMQ](https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md) to listen for wallet transactions and new blocks, replacing lightning's native [event subscriptions](https://github.com/GaloyMoney/galoy/blob/426eba9450963d9e423d9905d2f2a91a5d09319a/src/entrypoint/trigger.ts#L175).

Needed to continue with https://github.com/GaloyMoney/galoy/pull/317

**Comment by jotapea** [comment]
Go with [v6](https://github.com/zeromq/zeromq.js/#zeromqjs-next-generation)? Using v5 for now, as it is still suggested in the [docs](https://zeromq.org/languages/nodejs/).

**Comment by nicolasburtey** [comment]
@jotapea ZeroMQ is already active on our bitcoind I believe. this is also how lnd is getting all its transactions.

**Comment by jotapea** [comment]
@nicolasburtey Thanks for the info (also updated the title).
