### ISSUE TITLE
Idiomatic organisation of types

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#347]
Currently we have 1 file:
```
src/types.ts
```

from which we import the types.

An idiomatic way to do this would be:
```
@types/globalTypes/index.d.ts
@types/globalTypes/xxx.d.ts
```

Like this typescript should pick up the types automatically without needing to import them.

**Comment by vindard** [comment]
I can take a look at this

**Comment by vindard** [comment]
> Like this typescript should pick up the types automatically without needing to import them.

@bodymindarts just to be clear on this, is this issue asking that we stop explicitly importing types and rather have _all our own declarations_ available globally as well?

I started looking into this approach and it seems that one problem that would need to be managed is namespace clashes. For e.g. if the type exists globally already and someone re-declares it locally, I believe the existing global type simply gets extended, which can lead to some potential unexpected behaviours.

**Comment by vindard** [comment]
**_I've started playing with an implementation of this [in this branch](https://github.com/vindard/galoy/compare/config-refactor/specter...vindard:typing/global)_**

Next steps:
- remove non-type values and bring over more of the types/interfaces from `types.ts`
- resolve some issues I'm having when including `import` statements in the `index.d.ts` file
- figure out which is better between using `"paths"` or `"typeRoots"` in the `tsconfig.json` file and figure out if `node_modules` and any other dirs need to be explicitly included in that setting

**Comment by bodymindarts** [comment]
Some thoughts on this topic. I have to say I actually like explicit imports in general. It makes it easier to see the dependencies of file.
Am I correct in assuming that the dependency graph will still be clearly identifiable from the remaining imports even with global types?
I am a bit worried that global types will make it harder to detect things like circular dependencies.

That being said I think we certainly should adopt what is generally accepted as an idiomatic style from the ts community. @samerbuna has the most ts experience and is advocating for this approach. Could you perhaps post a link to 1 or 2 projects you consider doing this in an idiomatic way so we have something to refer too in this consideration?

I completely agree with the explicit type names argument regardless of scoping.
Will namespaces for types imported from 3rd parties mitigate the type shadowing issue? Would it be hard / break with idiomatic practice to also use namespaces in our own code?

**Comment by vindard** [comment]
I just added some additional notes to the [**'Notes ( :leaves:  evergreen)'**](https://github.com/GaloyMoney/galoy/issues/347#issuecomment-884244772) comment above on:
- _importing/exporting_ in global declaration files
- global type declarations as recommended practice
