### ISSUE TITLE
receive USD over lightning (client side)

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#350]
Currently we can only receive BTC over lightning. 

For the sake of clarification, when mentioning receiving USD over lightning, this means BTC is still the medium of exchange, but USD is the unit of account. 

To be able to do this currency conversion, there needs to be a dynamic hedging on an exchange, which is [work in progress](https://github.com/GaloyMoney/galoy/pull/349). 

This ticket here is relative to the client side: how can a user through our API can received USD instead of BTC.

There are multiples scenarios each with its own specifics in regards to price risk:
- amountless invoice / sendtoUsername
- invoice with amount
- onchain transaction

**amountless invoice / sendtoUsername**
Probably the easiest is the "amountless invoice" or "sendtoUsername" use case. 

It is the easiest is because there is no need to give a "free option" (in the finance sense, ie: give the payer the choice to pay this invoice in the next XX seconds/minutes, knowing that the price could change in the meantime) to the payer. rather the BTC/USD price to be used is determined when the funds are being received.

A small spread should be applied to cover the exchange fees

**invoice with amount**
If the payee is settings an amount, then we should:
- have a higher spread because the payer then can decide to pay or not pay depending of how the price move during the time the invoice is valid
- shorten the validity of the invoice from 1 day to something like 1 minute

eventually the spread should be dynamic depending on the market condition. if this is a very volatile market, we should have a higher spread than if this is a calm market. for now we can probably start with a simple number. 

**onchain transaction**

We can probably do the onchain transaction at a later stage. For onchain transaction, we can also have an amount in the QR code or not have an amount, so the pattern is similar to lightning invoice that can have an amount or be amountless. 

The main different with Onchain is the time to settlement. It can takes days/weeks for a transaction to arrive, so generally I think it's better to apply the price at the time the transaction get mined with X confirmations.

**Other**
[Price](https://github.com/GaloyMoney/price) is what is being used currently to do the USD/BTC conversion, this is a median of 3 exchanges. 

But if we're the counter part of the trade, maybe instead of using a median of 3 exchanges, we should rely on the single price of the exchange we'll be using to do the hedging?

**Comment by dolcalmi** [comment]
1st Stage - Ledger Refactor
- This is a minor refactor and the purpose is to have only one point of access to the ledger
- Some ledger actions are organized like ledger/transaction.ts but we need to unify the others
- MainBook (medici) instance must be only accessed inside ledger
- This change will allow to improve testing, maintainability and will make easier the add the USD transactions/balance

2nd Stage - Implement Lightning USD invoices and USD balance
- Implement basic module to get BTC/USD price to be used in the USD invoices (in this stage the current price implementation will be used but just for initial testing)
- Update addInvoice and related updating and send methods (with and without amount)
- Update/confirm that getBalance returns the new currency balance
- Add quote query for future use in mobile app
- Add currency filter to get transactions

3rd Stage - Advanced strategy for price 
- This needs to be done with the help of @sebastienverreault (must match or reduce risks for hedge strategy)
- We can have multiple strategies and enable them by configuration
- Must be and independent module

4th Stage - On chain USD 
- the same of the 2nd stage but with the difficult of the confirmation time.

@nicolasburtey please let me know if I am missing something

ps: each stage will be a PR

**Comment by nicolasburtey** [comment]
another task might be to convert usd from float to int (represented as cents)

**Comment by bodymindarts** [comment]
> another task might be to convert usd from float to int (represented as cents)

or custom `Money` type.

**Comment by nicolasburtey** [comment]
this ticket is no longer needed
