### ISSUE TITLE
Allow blocking IPs within a range

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy#361]

**Comment by dolcalmi** [comment]
using CIDR scheme?

**Comment by krtk6160** [comment]
> using CIDR scheme?

I was thinking of a simpler approach where we would just block the entire space, because of the issue highlighted by @nicolasburtey . For example -> 192.168.0.x should block that entire range (where x ranges from 0 to 255).

Using a CIDR scheme would definitely offer more flexibility, but I don't know if the higher complexity of implementing it makes sense. Something to discuss in our daily dev perhaps.

**Comment by dolcalmi** [comment]
maybe using this package https://github.com/sjinks/express-ip-filter-middleware (only has a dependency to ipaddr.js)

**Comment by nicolasburtey** [comment]
ip address related check has been moved out of galoy and can be managed by nginx directly if necessary
