### ISSUE TITLE
sats threshold to share memo

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#363]

**Comment by vindard** [comment]
We need to apply additional spam checks to the ones implemented in #415 to allow small value transactions from certain senders through the memo filter. The proposed approach is to mark any senders with the `funder` role as valid.

## Feature implementation proposal

### Problem
We need to improve the memo spam filter to allow small value transactions below the `MEMO_SATS_THRESHOLD` value to pass through the filter. Currently all transactions with values below that threshold get filtered. This filter gets applied in the translateDescription method in `tx-history.ts` by call it on each `LedgerTransaction` 'description' as transactions pass through the 'fromLedger' function.

On a `LedgerTransaction` object, I have the 'username' property of a user that I can optionally use to lookup the user's role.

'username' properties are unique for users.


### Proposed solutions
**Option 1**
I can add a check for the payer user's role to see if they are a valid role to allow through the filter. This means adding a db call for each parsed `LedgerTransaction`.

**Option 2**
I can fetch all the usernames from the database with the approved role and then check if the username matches the one on each `LedgerTransaction` as I parse the array.


### Proposed implementations

Spam filtering currently happens internally in the 'fromLedger' method inside the tx-history.ts domain file. It gets applied as a 'translateDescription' function on the 'description' property as transactions are parsed.

**Option 1**
  - implement a new `UsersRepository` method called `addPropertyToTransactions` that:
    - takes a `LedgerTransaction[]` array and a list of property names, and adds the properties to each transaction by querying for the user object in the db using the 'username' property on each `LedgerTransaction`
    - takes an optional filter function that itself takes a `LedgerTransaction` and returns True/False. We can use this to only make db queries for users on transactions that pass the filter.
    - optionally has an ephemeral object to track users already queried to avoid unnecessary db round trips
    - _Note: I believe this ends up working out to a decoupled JOIN on the Users and Transactions tables (collections)_

  - pass `ledgerTransactions` fetched from the ledger through this `addPropertyToTransactions` method before sending that object forward to `WalletTransactionHistory.fromLedger` in `getTransactionsForWallet` function
    - _Note: This potentially changes the type of object that the `fromLedger` method takes as an arg but the return should remain unchanged_

**Option 2**
  - implement a new UsersRepository method that finds all users for a given role
  - call the method and map over the result to isolate just the usernames into an array
  - pass the array into `WalletTransactionHistory.fromLedger` as a second argument to be used in the `shouldDisplayMemo` function for applying the additional check

**Comment by bodymindarts** [comment]
I think we should extract the `yes/no` memo logic into its own value object and pass that into the `fromLedger` function (similar to how we pass the `TxDecoder` to the `OnchainService`.

The `MemoFilter` object should be unit-tested and configurable including with an allow-list of usernames.
Getting / constructing the allow list should happen in the use-case method either via hard coded config or a call to the `UsersRepository`.
Something like
```
usersRepo.fetchAllUsersWithRole(role)
```
```

**Comment by vindard** [comment]
Question: do we still need to do this given that we're deprecating the `description` property from the `WalletTransaction` type? Is this still a backend concern?

**Comment by bodymindarts** [comment]
Yes we do since we will still share the `memo` field if it was added to a lightning invoice. The difference is it won't have the transformations logic that is applied to `description`. It will just be either shown or not depending on the filter.

**Comment by nicolasburtey** [comment]
@vindard this has been implemented?

**Comment by vindard** [comment]
I think we can close this now since no more active work is planned for it. We can always recreate if it comes up again.
