### ISSUE TITLE
Branded HTML emails

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/galoy#3634]
**Problem:** 
Our emails are plain text. They look cheap, unprofessional and untrustworthy. 

![image](https://github.com/GaloyMoney/galoy-mobile/assets/17384787/7f2f9959-33b5-4dae-b462-905aea845e10)

**Solution**: 
Branded HTML email.
- Confirmation code should be in email subject "Your confimration code in 123456"
- logo should be sourced from Galoy hosting

This template should be used for all email messaging towards user. 

![image](https://github.com/GaloyMoney/galoy-mobile/assets/17384787/ef711671-8cbc-462f-aae9-2ecb2b1f1f69)

**HTML:**
[HTML email.zip](https://github.com/GaloyMoney/galoy-mobile/files/13504771/HTML.email.zip)

**Comment by krtk6160** [comment]
@designsats This has been rolled out. It looks like this -

![image](https://github.com/GaloyMoney/galoy/assets/17320781/5dc8c072-d92b-4ef6-b217-777ecd324004)

Was wondering if the container should be centered, as that's what I have seen from other brands. We should probably also host the blink logo somewhere more reliable like github perhaps.

**Comment by nicolasburtey** [comment]
@krtk6160 maybe you miss my comment

- No quote needed around code
- tag under logo is too small imo

**Comment by nicolasburtey** [comment]
this has been addressed (but reopen is things are missing)
