### ISSUE TITLE
Dealer bot <-> core communication

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#369]
We want to extract the code related to the dealer bot from the core code base to remove complexity and isolate that functionality.

The main interactions of the dealer bot are accessible via the public API anyhow so we can treat the bot as "just another wallet user".

So far the flow would go as follows:
- user deposits BTC
- user decides to transfer x BTC into USD
- that amount of BTC will be internally transferred into the `USD hedging` wallet (under control from the trading bot).
- the trading bot will then have autonomy in deciding how much BTC it will transfer in / out of the wallet and what instruments to buy on which exchanges

The required functionality of `send` and `receive` BTC and finding out its own `BTC` balance is already present.

1 additional piece of information the trading bot needs to know is how much USD value it is supposed to ensure (via hedging or some other method).

There is an open question regarding how the trader can discover the `targetUSDValue` of the funds it controls.

Options:
a) add it as a Query field to GraphQL
b) expose it via another endpoint - for example as a GRPC call
c) publish it as a message to a msg queue - for example via Redis

I don't like a) because this is an inherently _internal_ and _use-case specific_ piece of information. I love GraphQL as a public API layer but would prefer to see other methods for internal use-cases. Adding a queryable field to the schema exposes that this internal-only field exists. It would also require custom logic in the GraphQL layer for dealing with the trader-bot only query which adds complexity. If we have other internal use cases that we chose to add to the GraphQL layer this would quickly add a lot of complexity and logic for dealing with the internal only stuff.

That being said I could see a case for adding it to the admin schema as this is already an API that has special treatment (pending ongoing work to extract it into a separate process) and exposing this information there might also be interesting for the admin.

If we don't add it to the public api but want to have a distinct way of serving internal-only use cases I think c) has the advantage that it introduces less coupling and less code.
- If the trader just listens to a Redis stream it would require no changes if the source or method for publishing the information would change. Thinking of enterprise integrations being able to change the source may be an advantage.
- The core code base already has a dependency on a client to interact with redis so adding code to push a message is a lot less complex than serving an additional endpoint like GRPC.

**Comment by nicolasburtey** [comment]
one another piece of information that I had come up this morning is that eventually the dealer pod should have a way to flow back information to the main app with some input on the price/spread. if the dealer have too little or too much coverage, then this should influence the spread. ie: if the dealer is overexposed in USD for whatever reason (let's say the exchange we use is down), the spread to go USD to BTC should be low (or even negative) and the spread to go to USD should be high.

**Comment by dolcalmi** [comment]
`1 additional piece of information the trading bot needs to know is how much USD value it is supposed to ensure (via hedging or some other method).`

@nicolasburtey is this what we talk about having a negative usd balance in the dealer/hedge wallet? @bodymindarts if so will be just another record in the balance query (I think is wallet2 graphql query) of the hedge wallet (it will be a negative value in usd to be able to match with the user wallets liabilities). Also, in regards to communication we can use somthing simple as [long polling](https://www.apollographql.com/docs/react/data/queries/#polling) or if we need better performance maybe need to add and additional API interface (Websockets or GRPC like @bodymindarts mention)

**Comment by nicolasburtey** [comment]
yes correct. I'm all for starting with the graphql API to get started on my end (and if we need more performance then we can switch to GRPC or redis)

**Comment by bodymindarts** [comment]
> @nicolasburtey is this what we talk about having a negative usd balance in the dealer/hedge wallet? @bodymindarts if so will be just another record in the balance query (I think is wallet2 graphql query) of the hedge wallet (it will be a negative value in usd to be able to match with the user wallets liabilities). Also, in regards to communication we can use somthing simple as long polling or if we need better performance maybe need to add and additional API interface (Websockets or GRPC like @bodymindarts mention)

I think there are 2 discussions going on, 1 is regarding semantics the other is regarding communication protocol.

## Re Semantics
I am very much against using an idea like `negative USD wallet balance signifies total user liabilities`. We have an explicit use case here `total galoy instance USD liabilities` and which ever method we use to retrieve this information should be explicitly named to communicate that _specific_ intent.

So far we have not introduced the idea that a `balance` that can be negative and also a balance is always something concrete that is connected to an individual user / agent. Having a `negative balance` here would be introducing custom logic on this field (meaning increased complexity) only needed for this use case and using the idea of `negative balance` this way would also increase the cognitive load trying to grok what's going on due to the implicit nature of the naming.

Having the dealer be `just another wallet user` (to simplify implementation because it can use the same code paths) would break here by introducing the special case.
Now the dealer is `just another wallet user that can also have a negative USD balance that signifies the total USD liabilities of all other users`. This is *not* `just another wallet user`.

## Re Communication protocol
There are a few reasons why I prefer redis here
- Segregate public / externally accessible (GraphQL) from non-public information passing
- Avoid circular dependencies. Especially if we have a bi-directional flow of information (like Nicolas mentioned might be the case) we do not want to couple to specific endpoints but only to generic messages.
- Long term it allows us the most extendability because there is no coupling to the source of the information, only to the message. So we can easily switch out both how the information is published and what consumes it. This opens up many many possibilities for enterprise integration
- Much less complexity than adding an additional endpoint like GRPC

Wether or not going with redis would be a performance boost is irrelevant for me.

**Comment by samerbuna** [comment]
I don't fully understand this but if the bot is to be _just another wallet user_ then I don't see why it shouldn't _just use the core API_.

I prefer to have all communications done with GraphQL. If a user or group of users will be using ONLY a specific set of operations that are special to them, then introducing a new GraphQL schema for them might be the way to go, but introducing other _types_ of data communication channels, in my opinion, will give us headache in the future.

**Comment by nicolasburtey** [comment]
> So far we have not introduced the idea that a balance that can be negative and also a balance is always something concrete that is connected to an individual user / agent. Having a negative balance here would be introducing custom logic on this field (meaning increased complexity) only needed for this use case and it would also increase the cognitive load trying to grok what's going on due to the implicit nature of the naming.

note: this logic is already into the app: https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/userWallet.ts#L64

just not exposed currently to graphql/redis because we just decide to remove the dealer out of the main repo some days ago

I so far generally agree with @samerbuna about the complexity of adding a new communication layer for the dealer is not what I would want to do (unless for performance reason we need it, but I don't think that will be the case)

**Comment by bodymindarts** [comment]
> I so far generally agree with @samerbuna about the complexity of adding a new communication layer for the dealer is not what I would want to do (unless for performance reason we need it, but I don't think that will be the case) therefore graphql is what I would advocate for now

I have reflected on this some more and realised I am biased towards asynchronous message passing for internal communication as an architectural style because of the desirable properties that emerge from these systems such as:
- less coupling
- easier to extend
- easier to scale
- etc.

But the issues that this style solves for are typically only observed once a system has achieved a certain size.
I do concede that having 2 mechanisms for sharing information increases complexity and I'm not sure at this point wether the galoy system as a whole will reach the size threshold where moving to an asynchronous architecture becomes mandatory in order to deal with the issues of synchronous communication and higher levels of coupling. That is the - long-term benefits may not merit the short term complexity increase if the system stays small to medium overall.

That being said, even choosing to stick with GQL there is still the open question of semantics and treatment of dealer specific logic. I would consider the quoted line you mention (special treatment of individual instances of a class) to be an anti-pattern
```
      // the dealer is the only one that is allowed to be short USD
      if (this.user.role === "dealer" && id === "USD") {
        assert(balance <= 0)
      } else {
        assert(balance >= 0)
      }
```
perhaps a topic for code-review

**Comment by nicolasburtey** [comment]
> I have reflected on this some more and realised I am biased towards asynchronous message passing for internal communication as an architectural style 

could be a good way to sum it up indeed. 

keeping in mind here that there is a single client (dealer) accessing a single backend (graphql) for fetching one value (USD balance, basically a INT) every couple of seconds or so, so the complexity of asynchronous message (I guess you're referring a message queue?) is clearly not needed in my opinion

**Comment by nicolasburtey** [comment]
> perhaps a topic for code-review

happy to expend on this during the next code review if that's helpful. I've discussed about it with @sebastienverreault and @dolcalmi already in the last couple of days. To really understand the context of this exception though, it's important to also understand the finance aspect of the dealer, and why the dealer is the only wallet that can be short USD.

**Comment by bodymindarts** [comment]
> keeping in mind here that there is a single client (dealer) accessing a single backend (graphql) for fetching one value (USD balance, basically an INT) every couple of seconds or so, so the complexity of asynchronous message (I guess you're referring to a message queue with buffer capability?) is clearly not needed in my opinion

At this point I am inclined to agree (like I mentioned) but I don't think it is `completely clear`. It really depends on the strategy we want to use for extendability and integrations. But we can visit that discussion when there is a 'real' use-case coming from a real request for integration. Better to keep it simple for now.

> happy to expend on this during the next code review if that's helpful. I've discussed about it with @sebastienverreault and @dolcalmi already in the last couple of days. To really understand the context of this exception though, it's important to also understand the finance aspect of the dealer, and why the dealer is the only wallet that can be short USD.

Yeah we really need to dig into this because up to now I do not see any benefit in treating this as a special case vs an explicit concept.
Since we are on the topic of reducing complexity - every conditional in the system increases the (cyclomatic complexity)[https://en.wikipedia.org/wiki/Cyclomatic_complexity] of a system which in turn is strongly correlated with the number of defects and how difficult it is to test. Saying "yes but its just this 1 special case" is a very slippery slope.

**Comment by bodymindarts** [comment]
This has been addressed in the GQL v2 redesign
