### ISSUE TITLE
updatePendingPayments lock issue

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#375]
### Description
Lock async function is executed multiple times with same data when "pay hodl invoice" test is running (seems that lock not acquired or acquired and is retaining db data). [This is the `redlock` block used in updatePendingPayments of `src/Lightning.ts`](https://github.com/GaloyMoney/galoy/blob/main/src/Lightning.ts#L692) 

### Implications

- If that lock does not work then a payment can be processed or void multiple times (including fees deductions in directPay) so we did a fix for this [here](https://github.com/GaloyMoney/galoy/pull/368)
- If the problem is really redlock or our wrapper then we need to validate its implications in other functionality

**Comment by nicolasburtey** [comment]
should be fixed by https://github.com/GaloyMoney/galoy/pull/376
