### ISSUE TITLE
Structured migrations

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/galoy#383]
Having to run schema migrations in production is a recurring task that we need a structured, deterministic approach too.

We should investigate a long-term solution so that we don't rely on 1-off db-scripts every time a migration is necessary.

Considerations:
- can we use a library that takes care of this?
- can we use a library that isn't coupled to mongoose (since we may not want to use mongoose long-term)?
- if we cannot use a library we should implement it ourselves (it isn't that complicated) using the standard pattern of an up/down script per migration and a `migrations` table in the database to document which have been executed.

**Comment by nicolasburtey** [comment]
@bodymindarts we use migrate-mongo so far for info.

https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/package.json#L104

https://github.com/GaloyMoney/galoy/blob/main/src/migrations/20210610073725-multi-lnds.ts

the script is just manually for now and should be integrated as part of the CD flow

**Comment by bodymindarts** [comment]
Migrations structure already in place just need to differentiate between new instances vs existing instances.

**Comment by nicolasburtey** [comment]
we have something now. closing this generic ticket.
