### ISSUE TITLE
Running the project locally fails

### ISSUE THREAD

**Issue by jotapea** [GaloyMoney/galoy#399]
Running the project locally on the current main (cca971df) is broken. The following errors happen:

`$ cd galoy`
`$ direnv allow`

`$ make start` or `$ make watch`

>Compilation error in /Users/juanaleman/scratch/galoys/galoy/src/entrypoint/graphql-core-server.ts
[ERROR] 13:36:45 ⨯ Unable to compile TypeScript:
src/entrypoint/graphql-core-server.ts(115,38): error TS2304: Cannot find name 'Primitive'.

Then after a hack to move on (redefining the type in `graphql-core-server`

`
type Primitive = string | boolean | number
`

the following error happens:

>Compilation error in /Users/juanaleman/scratch/galoys/galoy/src/config.ts
[ERROR] 13:42:31 ⨯ Unable to compile TypeScript:
src/config.ts(24,43): error TS2304: Cannot find name 'ITransactionLimits'.
src/config.ts(40,33): error TS2304: Cannot find name 'IRateLimits'.
src/config.ts(63,44): error TS2304: Cannot find name 'UserWalletConfig'.
src/config.ts(75,43): error TS2304: Cannot find name 'SpecterWalletConfig'.
src/config.ts(86,22): error TS2304: Cannot find name 'Levels'.

**Comment by jotapea** [comment]
@vindard

**Comment by vindard** [comment]
I couldn't replicate the error until I noticed I didn't have [`tsnd`](https://github.com/GaloyMoney/galoy/commit/6df62a4598d35d8a8f6e6b6fde89f7472a9ed514#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L6) in the `Makefile` and then I ran `yarn install` again to grab it. It looks like that change may be what's causing the error where the type declaration files aren't being automatically imported now.

I'll check this out and see what I can find.

**Comment by vindard** [comment]
@samerbuna it looks like we have another little global typing issue with `ts-node` being introduced ([details here](https://github.com/TypeStrong/ts-node#help-my-types-are-missing)). Do you have any ideas on how we can easily solve without doing things like restructuring the types again as they suggest?
