### ISSUE TITLE
Feature Request: Auto generate the graphQL string including the API key for BTC Pay Server Integration

### ISSUE THREAD

**Issue by ThinusXpressed** [GaloyMoney/galoy#4010]
**Is your feature request related to a problem? Please describe.**
When creating a link between BTC Pay Server and Blink via graphQL to setup a lightning node; copying and pasting the API
key into the network configuration is a huzzle considering the string needs to be manualy adjust to get the correct format and it's easy to make a mistake or have a typo.

You have to recreate this:

![image](https://github.com/GaloyMoney/galoy/assets/121315637/8e4b2c17-1d82-4b34-901e-ccc91ad19803)

and then add the API key:

![image](https://github.com/GaloyMoney/galoy/assets/121315637/5124a632-08d5-4f4e-9746-6626e96321af)

**Describe the solution you'd like**
My suggestion would be to add a button that auto generate the graphQL string including the API key that can just be copied from the Blink Dashboard and Pasted on the BTC Server Side... This will make it a one step process and eliminate possible mistakes...

![image](https://github.com/GaloyMoney/galoy/assets/121315637/2b628eae-9fae-4936-aee3-6a800ad2e96b)

that can then just be pasted here in the correct string format:

![image](https://github.com/GaloyMoney/galoy/assets/121315637/5f55f5e2-f07e-4e42-a706-5c2ba60777ee)

**Describe alternatives you've considered**
///...

**Additional context**
///...

**Comment by nicolasburtey** [comment]
the `copy graphql string` would be for btcpay server only, right? so it should be more a `copy settings for btcpay server`?

**Comment by nicolasburtey** [comment]
probably need to be on the previous screen, because we don't show the key anymore on the screen you have screenshoted @ThinusXpressed

**Comment by ThinusXpressed** [comment]
> the `copy graphql string` would be for btcpay server only, right? so it should be more a `copy settings for btcpay server`?

Correct!

**Comment by ThinusXpressed** [comment]
> probably need to be on the previous screen, because we don't show the key anymore on the screen you have screenshoted @ThinusXpressed

This would be fine as long as the correctly combined graphQL + API Key is generated and copied to the clipboard.

**Comment by nicolasburtey** [comment]
this has been deployed
