### ISSUE TITLE
Batch Payments: Disregard line in csv when amount is set to 0

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy#4019]
For users who are reusing a template with multiple usernames for batch payments, just setting amount to zero when individual recipients in template should not get paid in current batch payment because it's easier to set amount to zero than remove a line from csv. 

It would be more convenient for folks who do recurring batch payments with same template.

**Comment by nicolasburtey** [comment]
What is the effect currently when amount is zero? Error?

**Comment by siddhart1o1** [comment]
> What is the effect currently when amount is zero? Error?

Yes, We stop user on CSV validation step.
