### ISSUE TITLE
create a layer of abstraction between wallets and users

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#403]
currently users have one wallet. we want the possibility for users to have multiple wallet.

currently, if a user have a BTC + USD wallet (USD is not deployed yet, but the way it has been designed), this would be the same `account_path` in medici, but with different currency.

When fetching the ledger for a particular wallet, the currency is being specified. so even if the wallet shared the same `account_path` today, this solution only scale to 1 wallet/currency/user.

One way to create a more scalable solution and let the user (which could be corporate user) is to have multiple wallet per user. with this architecture, there is no longer a need to have 2 different currency per `account_path`. each wallet would have it's own currency. 

as part of this redesign, we'll want to figure out what should be part of the user, what should be part of the wallet. for instance, should the username be attached to the user or the wallet?

if as a user, I want to be able to receive both USD and BTC depending of the payment, then the username is not enough. maybe we can have a `username#wallet` type, and if the `#walletname` is not provided, then we use the default wallet from the user.

**Comment by dolcalmi** [comment]
related to [issue 350](https://github.com/GaloyMoney/galoy/issues/350)

**Comment by dolcalmi** [comment]
findings so far:

- We will need to extend current user schema/class to add multiple wallets and common validations (like limits)
- We need to decouple User from the lightning and onchain classes/mixin
    - abstract or refactor functionality that use user id, username, limit validations, finds (for internal transfers) and account path (ledger)
    - in practical terms: `user`<sup>1</sup>-> <sup>*</sup>`wallet` <sup>1</sup> <-> <sup>1</sup> `ledger account path` 
- Default wallets: We can use the current username and map it to the first wallet of each currency, so for the end-user will be the same behavior. If we like we can add a setting to setup the default wallet but I think is not necessary.  
- addEarn need to be migrated to use default BTC wallet
- DB Migration:
    - The current `users` table needs to be renamed to `wallets` (this way we will not need to migrate ledger tables)
    - User related data (username, phone, deviceToken, earn, contacts, excludeCashback, language, lastIPs, twilio) needs to be used to create a new User table
    - We can create an intermediate table to map users to wallets (this is maybe better if we will have a different structure for companies) or add userId to wallets table

**Comment by vindard** [comment]
@nicolasburtey can we close this now with the new `Account` abstraction and ongoing refactors?
