### ISSUE TITLE
Add SAT for 'Settle Amount' to transactions table in dashboard

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy#4179]
Currently, there is only USD denomination, which is useful, but would like to see settlement amount in SATS, too, in this table.
![image](https://github.com/GaloyMoney/galoy/assets/32958103/81c3440d-94d8-4817-bc53-49aea0ffe709)

**Comment by nicolasburtey** [comment]
maybe it's a use case best serve by downloading the CSV?

**Comment by pretyflaco** [comment]
Maybe there's a marginal case where no actual sets are sent, but in most cases there are sats moving. When running dollar denominated payroll daily, sats amounts are changing, but currently there is no visibility into this fluctuations. Downloading csv daily is cumbersome.

Also, not having sats in a bitcoin wallet interface is just weird.
