### ISSUE TITLE
Wallets.updateOnChainReceipt unhandled exception

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#504]
All methods that use `redlock` throw `LockError` exception if exceed 5 attempts to lock the resource.

The method should handle that exception and return an `ApplicationError`

**Comment by bodymindarts** [comment]
We should wrap `redlock` via a `DistributedLockService` or something like that translates the error.
I've noticed the lock actually gets used in different contexts once it locks a user and once it locks just an invoice I think. Those should be differentiated via methods on the `service`

**Comment by bodymindarts** [comment]
fixed via https://github.com/GaloyMoney/galoy/pull/489
