### ISSUE TITLE
Add new Admin mutations/queries to debug support requests

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#508]
- [ ] Search invoice/onchain tx receipt by hash (to verify status and if was credited to user)
- [ ] Search payment status by hash 
- [ ] Execute onchain/invoices receipt process (giving the option before/after block) -> Maybe this should be allowed for each cron task
- [ ] Get core wallets balances/transactions (at least the balance)
- [ ] Query Marketing wallet remaining balance
- [ ] Query SMS provider remaining balance
- [ ] Send last code to user with different SMS provider (not sure about this but has a lot of support requests)

@nicolasburtey @krtk6160 Do you think this could compromise security?

**Comment by krtk6160** [comment]
I think we should also discuss about whether the current user auth on admin panel is sufficiently secure before we implement additional features.

> @krtk6160 Do you think this could compromise security?

I don't think these features could compromise security, but they could compromise privacy.
