### ISSUE TITLE
use the htlc interceptor/hold invoice to simplify our logic around invoice

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#604]
currently, we have trigger that is listening to [invoice_update](https://github.com/GaloyMoney/galoy/blob/main/src/servers/trigger.ts#L204). but because lnd can settled an invoice when trigger is not running, or also because event with lnd are not garantee, we have an (expensive) fallback solution which is to [loop over all non-expired invoice](https://github.com/GaloyMoney/galoy/blob/19d125f25c8c64becbee922daae9cc14be6bdb94/src/app/wallets/get-balance-for-wallet.ts#L15) for a user that log in, and see if we miss any paid invoice. 

it's expensive because it adds strain to our lnd (n+1 requests), but also adds delay to the user when fetching their balance. 

since version lnd 11 or 12, lnd now have a [htlcinterceptor](https://api.lightning.community/#htlcinterceptor).

This could be use to simplify the logic on crediting users after an invoice has been paid.

The idea is simple: when a new htlc arrive, we can have trigger that is intercepting the htlc, and settled the user balance before validating the htlc. 

the only drawback to this logic is, in the unlikely event trigger is down, our node would not accept payment. but we could simplify the logic/state management a lot by implementing this.

**Comment by nicolasburtey** [comment]
do @vindard or @dolcalmi want to tackle this?

**Comment by nicolasburtey** [comment]
might probably worth waiting until this is merged for us to add the interceptor: https://github.com/lightningnetwork/lnd/pull/6232

otherwise the edge case where our pod intercepting the request is down could lead to force close

**Comment by joostjager** [comment]
>The idea is simple: when a new htlc arrive, we can have trigger that is intercepting the htlc, and settled the user balance before validating the htlc.

Note that the interceptor does not intercept htlcs on the final hop. Not sure if that is functionality that you require?

**Comment by nicolasburtey** [comment]
> Note that the interceptor does not intercept htlcs on the final hop. 

oh I thought that was the case. thanks for pointing that up.

Is there another API for that, or intercepting htlc as they're about to be settled is not available on an API for the time being?

I don't see too much of an issue in the long run because we'll by default seggregate the routing node and payment node (the payment will be behind a private channel), but it's not something we have done so yet. I guess we may want to start with that.

**Comment by joostjager** [comment]
Hodl invoice is the thing that comes closest.

But if you are redesigning your setup, you could also choose to work with a virtual final node key. So no payment node, just routing nodes. Via the htlc interceptor, htlcs to the virtual node are intercepted and matched against a central invoice database.

That way you can have fail over too. If one of the routing nodes goes down, the invoice remains valid and the sender will retry the payment via one of the other routing nodes.
