### ISSUE TITLE
add payment metadata to medici_transactions

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#605]
lnd 0.14 will have the capability to delete individual payments.

in the interest of making our node database smaller, we should take advance of this features and delete payment after they complete. 

that said, we will loose some data that we need to store beforehands.

Currently, for data analysis (ie: to know where payment are most frequently sent to), we are getting the individual payment using [trackpayment](https://api.lightning.community/#trackpayment) (using [listpayments](https://github.com/lightningnetwork/lnd/issues/5658) would get better but our node is currently failing with that)

now if we want to delete succesful payments, we need to store this metadata somewhere. I'm suggesting to store it alongside the medici transactions. we could store the json as a blob, and will extract/handle the data manually at a later stage in a data pipeline/data exploration environment.

I think both postgres and mongodb accept having a field as a json (mongodb even more so than postgres. the point is we don't need a structured schema for it)

**Comment by nicolasburtey** [comment]
maybe also @vindard or @dolcalmi can look over this

**Comment by vindard** [comment]
Adding implementation notes here, I believe we'd be persisting values from the returns of these two functions:
- https://github.com/alexbosworth/ln-service#payViaRoutes
- https://github.com/alexbosworth/ln-service#payviapaymentdetails

**Comment by dolcalmi** [comment]
> Adding implementation notes here, I believe we'd be persisting values from the returns of these two functions:
> 
> * https://github.com/alexbosworth/ln-service#payViaRoutes
> * https://github.com/alexbosworth/ln-service#payviapaymentdetails

these methods not always return a final state so we need to use getPayment (for ex in trigger), the only concern about this is that lightning library not always return all attributes from lnd node

**Comment by vindard** [comment]
Adding some other things we'd like to persist as well:
- [ ] Add preimage to `PayInvoiceResult` type and persist in medici (see [comment](https://github.com/GaloyMoney/galoy/pull/598#discussion_r721499238))

**Comment by nicolasburtey** [comment]
this is done

**Comment by nicolasburtey** [comment]
@vindard : "I'll double-check that cron deletes these from lnd"

**Comment by vindard** [comment]
> @vindard : "I'll double-check that cron deletes these from lnd"

It does, all good
