### ISSUE TITLE
move ccxt/price history out of the main repo

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#683]
now that we now longer have ccxt dependency in the main repo, we should have price history in an independant repo, so that we don't have to embedded ccxt in our main logic. 

- ccxt is a large repo (which could become a supply chain attack vector) and here we're only using it for fetching ohlcv. we could just use the api of the exchange directly
- we don't need to use mongodb for the price history. we could just have a simple pod and disk storage for it.

the data could be sent to the graphql pod either with GRPC, or just point to the disk storage.

this can be done after https://github.com/GaloyMoney/galoy/pull/662 is been merged. there is no urgency to do it.

**Comment by dolcalmi** [comment]
should we include price histoy in https://github.com/GaloyMoney/price/ ?

**Comment by nicolasburtey** [comment]
> should we include price history in https://github.com/GaloyMoney/price/ ?

we could. but ultimately they serve different purpose so this could be another pod.
