### ISSUE TITLE
make integration issue

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#689]
trying to run the integration test and this is failing. After debugging, it seems the issue is coming to the `fetch_macaroon()` function. 

`docker ps -q -f status=running -f name="${PWD##*/}_$1_"` is returning without any output. 

if I remove `-f name="${PWD##*/}_$1_"` then I have a list of container running. 

I am running/just updated my docker, and docker compose is v2. our documentation mention compatibility with v1, so maybe this is related. but v2 comes now installed by default so we should support it if this is the issue

**Comment by bodymindarts** [comment]
we have moved to docker compose v2
