### ISSUE TITLE
Tracing Service - Structure

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#696]
- Tracing service is being used in the app layer but is not defined in domain. It needs to be defined and add proper unit/integration tests
- Every import to tracing service (in app layer) is calling `provider.register()`. is this a problem? duplicates instrumentation data (we are calling it in the start command too)?

**Comment by bodymindarts** [comment]
> * Tracing service is being used in the app layer but is not defined in domain. It needs to be defined and add proper unit/integration tests

Tracing services is a cross cutting concern and not part of our domain IMO.
In terms of unit / integration I'm happy to discuss how you think this could work.

> * Every import to tracing service (in app layer) is calling `provider.register()`. is this a problem? duplicates instrumentation data (we are calling it in the start command too)?

I haven't seen this be an issue so far - no duplication of data is observed in logs or in upstream UIs. I'd say `register` is idempotent. We could of course split tracing into 2 files - one for registering and 1 for the helpers.

**Comment by nicolasburtey** [comment]
I think this ticket is stale/a lot has been done on tracing lately. we should reopen with more specific actions items if necessary
