### ISSUE TITLE
prepopulate the playground with some query

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#757]
currently if we open the playgound, we see an empty query field.

It would help developers to be able to have a query to go with when they first open the page.

I don't know if/how this could be done, but it would be useful to have also all the queries that are [here](https://galoymoney.github.io/galoy/#intro-item-0)

**Comment by nicolasburtey** [comment]
looking at github: https://docs.github.com/en/graphql/overview/explorer

there is an additional tab called "Explorer" which make it extra easy to add/create a query or a mutation.

![image](https://user-images.githubusercontent.com/11156370/143501939-1813b2bb-c4b1-460e-aa3d-2ca1a4e3ce87.png)

the Explorer tab is not part of our playground.

**Comment by moksha256** [comment]
@nicolasburtey assuming [this](https://api.staging.galoy.io/graphql) is the playground we're talking about, and [this](https://github.com/GaloyMoney/galoy/blob/1ed5feb03b2870b81e5352db2ae8ba522055a45d/src/servers/graphql-server.ts#L149) where it's configured, it looks like we should be able to add a `tabs` property with a `query` specifying default text ([reference](https://www.apollographql.com/docs/apollo-server/v2/testing/graphql-playground/#configuring-playground)).

Is that correct? If it is, I can make a pull request.

**Comment by nicolasburtey** [comment]
this issue has been done
