### ISSUE TITLE
Add payment secret for invoices and payments

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy#764]
please check  https://github.com/GaloyMoney/galoy/pull/759#discussion_r757837347 and https://github.com/GaloyMoney/galoy/pull/759#discussion_r757771447

**Comment by nicolasburtey** [comment]
@vindard I think this one has been completed?

**Comment by vindard** [comment]
> @vindard I think this one has been completed?

I linked PR #1077 to close this one out

**Comment by nicolasburtey** [comment]
this has been added AFAIK
