### ISSUE TITLE
walletId - publicWalletId mismatch between layer

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#781]
https://github.com/GaloyMoney/galoy/pull/766/files#r760603642

**Comment by bodymindarts** [comment]
While I generally agree it is useful to align the naming - keep in mind that this is not mandatory. GraphQL layer should be coupled to and serve the needs of external clients. The domain layer should be optimal to represent our business logic. When these 2 goals diverge there needs to be mapping.

Though I don't see that that needs to be the case here.

**Comment by nicolasburtey** [comment]
this is uber confusing: `{walletPublicId: walletId}`

**Comment by nicolasburtey** [comment]
this has been addressed with https://github.com/GaloyMoney/galoy/pull/808
