### ISSUE TITLE
Latency in calls to MainQuery

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy#793]
@nicolasburtey experienced a period of latency between making an onchain payment and seeing his balance update in the app.  I checked a trace of the call to the MainQuery from @nicolasburtey user [here](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/vdLxTcjzHZy/trace/EXCRs7tuv2c?span=86bd7f1592fa09b2).  We can see that the trace contains a lot of http calls to `https://fcm.googleapis.com/fcm/send`, but as these seem to be asynchronous we don't think this is the cause of the latency. Instead it seems to be coming from the part of the code which fetches the current balance which loops through all the unpaid invoices / unprocessed payments.  More investigation is needed to confirm but we need to trim down the time it takes to make this call as it's the main query we use in the app to display all of the data to the user so it should never take 3.5 seconds to respond.

**Comment by daviroo** [comment]
@nicolasburtey thinks it might be related to the issue discussed in #604 but it's probably worth looking into other aspects as the delay might be coming from multiple places.

**Comment by nicolasburtey** [comment]
the problem has been amplified by the fact `trigger` was offline since yesterday migration. let's look at https://github.com/GaloyMoney/galoy/issues/604 as a potential solution?

**Comment by dolcalmi** [comment]
this https://github.com/GaloyMoney/galoy/commit/c5c64c8acea9075525e0d363293c6bd81205ee61 could help too. We are querying 360 blocks for pending incoming on-chain txs (in theory we need only 1 day max, if cron is running 😅 )

**Comment by vindard** [comment]
@dolcalmi could we maybe do something like the `runInParallel` function you introduced a while back too?

I noticed from honeycomb that each `updatePendingInvoice` seems to happen sequentially, and I couldn't quite figure how to collect a bunch of promises from the async generator in that loop and fire them all off in a `Promise.all` or something similar 🤔

**Comment by nicolasburtey** [comment]
most/(all?) of the significant latency issues has been addressed over the last 2 weeks. closing this for now. we can reopen if needed.
