### ISSUE TITLE
No user with `role: editor` gets created during bootstrap

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy#909]
It looks like we are no longer creating the "editor" user that's being passed in the test_accounts array. I see we are doing something with the funder, dealer and bankowner [here](https://github.com/GaloyMoney/galoy/blob/main/src/services/mongodb/index.ts#L11), but I don't know if that's where we need to add logic to include the admin user as well.

**Comment by nicolasburtey** [comment]
is that still an issue @krtk6160 ?

**Comment by krtk6160** [comment]
@nicolasburtey Yes it is, but the title of the issue is not quite accurate, I'll modify it. We should add the `editor` user to the bootstrap migration script and the integration tests so that it also gets created along with the other mandatory accounts, and not in `test_accounts`.

**Comment by nicolasburtey** [comment]
we're moving away from test_accounts and going to use oauth2 and client_credentials in admin panel auth so closing as a no_fix
