### ISSUE TITLE
subcription may not be working for intraledger tx

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#934]
to reproduce:

- open https://api.staging.galoy.io/graphql
- get a JWT by login in, add it to the headers
- use the following subscription:

```
subscription myUpdates {
    myUpdates {
      errors {
        message
      }
      me {
        id
        defaultAccount {
          id
          wallets {
            id
            walletCurrency
            balance
          }
        }
      }
      update {
        type: __typename
        ... on LnUpdate {
          paymentHash
          status
        }
        ... on OnChainUpdate {
          txNotificationType
          txHash
          amount
          usdPerSat
        }
        ... on IntraLedgerUpdate {
          txNotificationType
          amount
          usdPerSat
        }
      }
    }
  }
```

from the mobile app, do some quizzes. there is no updates being sent by the subscription

note: 
- it could be that this is only for quizzes question because it using internally another path than the one that originate from a "pay to username" AFAIR
- I have tried invoice and this is working.
- I have not tested the onchain tx.

**Comment by samerbuna** [comment]
I also found that it's not working for the sender which it should. I'll get it fixed.

**Comment by nicolasburtey** [comment]
has this been fixed @samerbuna ?
